# Generated by Django 2.2.7 on 2019-11-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('fname', models.TextField()),
                ('mname', models.TextField()),
                ('lname', models.TextField()),
                ('short_bio', models.TextField()),
                ('long_bio', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teamim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.TextField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tssite.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=256)),
                ('division_name', models.CharField(max_length=256)),
                ('division_title', models.CharField(max_length=256)),
                ('division_sponsor', models.CharField(max_length=256)),
                ('division_sequence', models.CharField(max_length=256)),
                ('segment', models.CharField(max_length=256)),
                ('segment_name', models.CharField(max_length=256)),
                ('segment_title', models.CharField(max_length=256)),
                ('segment_sponsor', models.CharField(max_length=256)),
                ('segment_sequence', models.CharField(max_length=256)),
                ('section', models.CharField(max_length=256)),
                ('section_name', models.CharField(max_length=256)),
                ('section_title', models.CharField(max_length=256)),
                ('section_sponsor', models.CharField(max_length=256)),
                ('section_sequence', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
                ('unit_name', models.CharField(max_length=256)),
                ('unit_title', models.CharField(max_length=256)),
                ('unit_sponsor', models.CharField(max_length=256)),
                ('unit_sequence', models.CharField(max_length=256)),
                ('part', models.CharField(max_length=256)),
                ('part_name', models.CharField(max_length=256)),
                ('part_title', models.CharField(max_length=256)),
                ('part_sponsor', models.CharField(max_length=256)),
                ('part_sequence', models.CharField(max_length=256)),
                ('series', models.CharField(max_length=256)),
                ('series_name', models.CharField(max_length=256)),
                ('series_title', models.CharField(max_length=256)),
                ('series_sponsor', models.CharField(max_length=256)),
                ('series_sequence', models.CharField(max_length=256)),
                ('start_chapter', models.CharField(max_length=256)),
                ('start_verse', models.CharField(max_length=256)),
                ('end_chapter', models.CharField(max_length=256)),
                ('end_verse', models.CharField(max_length=256)),
                ('audio_url', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('video_url', models.CharField(max_length=1024)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tssite.Teacher')),
                ('teamim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tssite.Teamim')),
            ],
        ),
    ]
