# Generated by Django 2.2.7 on 2019-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
