# Generated by Django 2.2.7 on 2019-11-17 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0002_auto_20191114_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short_bio',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
