# Generated by Django 2.2.7 on 2019-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0003_auto_20191117_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
