# Generated by Django 2.2.7 on 2019-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0004_auto_20191117_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mname',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
