# Generated by Django 2.2.7 on 2019-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0006_auto_20191117_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
