# Generated by Django 2.2.7 on 2019-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0007_auto_20191117_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
