# Generated by Django 2.2.7 on 2019-11-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0011_auto_20191117_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
    ]
