# Generated by Django 2.2.7 on 2019-12-06 04:36

from django.db import migrations, models
import django.db.models.deletion
import tssite.models
import tssite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0016_auto_20191117_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='audio',
            field=models.FileField(default=None, null=True, upload_to=tssite.models.get_class_audio_location, validators=[tssite.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='teamim',
            name='reader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.Teacher'),
        ),
    ]
