# Generated by Django 3.0.3 on 2020-02-16 23:12

from django.db import migrations, models
import tssite.models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0020_auto_20200216_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamim',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=tssite.models.common.get_teamim_audio_location),
        ),
    ]
