# Generated by Django 3.0.3 on 2020-02-16 23:15

from django.db import migrations, models
import tssite.models.common
import tssite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0021_auto_20200216_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='audio',
            field=models.FileField(default=None, max_length=500, null=True, upload_to=tssite.models.common.get_class_audio_location, validators=[tssite.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='teamim',
            name='audio',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tssite.models.common.get_teamim_audio_location),
        ),
    ]
