# Generated by Django 3.0.3 on 2020-03-18 04:00

from django.db import migrations, models
import django.db.models.deletion
import tssite.models
import tssite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0022_auto_20200216_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalmudSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=1024)),
                ('line_two', models.CharField(max_length=1024)),
                ('line_three', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TalmudStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seder', models.CharField(choices=[('zeraim', 'Zeraim'), ('moed', 'Moed'), ('nashim', 'Nashim'), ('nezikin', 'Nezikin'), ('kadashim', 'Kadashim'), ('taharot', 'Taharot')], max_length=12)),
                ('seder_sequence', models.IntegerField(blank=True, null=True)),
                ('masechet', models.CharField(choices=[('berachot', 'Berachot'), ('shabbat', 'Shabbat')], max_length=50)),
                ('masechet_sequence', models.IntegerField(blank=True, null=True)),
                ('daf', models.IntegerField()),
                ('amud', models.CharField(choices=[('a', 'a'), ('b', 'b')], max_length=1)),
                ('audio', models.FileField(default=None, max_length=500, null=True, upload_to=tssite.models.common.get_talmud_audio_location, validators=[tssite.validators.validate_file_extension])),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amud_sponsor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='tssite.TalmudSponsor')),
                ('daf_sponsor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='tssite.TalmudSponsor')),
                ('masechet_sponsor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='tssite.TalmudSponsor')),
                ('seder_sponsor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='tssite.TalmudSponsor')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.Teacher')),
            ],
        ),
    ]
