# Generated by Django 3.0.3 on 2020-03-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0023_talmudsponsor_talmudstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talmudstudy',
            name='masechet',
            field=models.CharField(choices=[('Zeraim', (('shabbat', 'Shabbat'),)), ('Moed', (('berachot', 'Berachot'),))], max_length=50),
        ),
    ]
