# Generated by Django 3.0.3 on 2020-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0024_auto_20200319_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talmudsponsor',
            name='line_three',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='talmudsponsor',
            name='line_two',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
