# Generated by Django 3.0.3 on 2020-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0026_auto_20200320_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talmudstudy',
            name='amud',
        ),
        migrations.RemoveField(
            model_name='talmudstudy',
            name='amud_sponsor',
        ),
        migrations.AlterField(
            model_name='talmudstudy',
            name='masechet',
            field=models.CharField(choices=[('Zeraim', (('berachot', 'Berachot'),)), ('Moed', (('shabbat', 'Shabbat'),))], max_length=50),
        ),
    ]
