# Generated by Django 3.0.3 on 2020-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0027_auto_20200322_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['series_sequence', 'division_sequence', 'segment_sequence', 'section_sequence', 'unit_sequence', 'part_sequence', '-date']},
        ),
        migrations.AlterField(
            model_name='class',
            name='segment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
