# Generated by Django 3.0.3 on 2020-05-10 15:53

from django.db import migrations, models
import django.db.models.deletion
import tssite.models.mishna
import tssite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0027_auto_20200322_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='MishnaMasechet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sequence', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MishnaSeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sequence', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=1024)),
                ('line_two', models.CharField(blank=True, max_length=1024, null=True)),
                ('line_three', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['series_sequence', 'division_sequence', 'segment_sequence', 'section_sequence', 'unit_sequence', 'part_sequence', '-date']},
        ),
        migrations.CreateModel(
            name='MishnaStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perek', models.IntegerField()),
                ('mishna', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('audio', models.FileField(default=None, max_length=500, null=True, upload_to=tssite.models.mishna.get_mishna_audio_location, validators=[tssite.validators.validate_file_extension])),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('masechet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tssite.MishnaMasechet')),
                ('seder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tssite.MishnaSeder')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='mishnaseder',
            name='sponsor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.Sponsor'),
        ),
        migrations.AddField(
            model_name='mishnamasechet',
            name='sponsor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.Sponsor'),
        ),
    ]
