# Generated by Django 3.0.3 on 2020-05-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0028_auto_20200511_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='division_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='part_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='section_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='segment_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='series_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='unit_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
