# Generated by Django 5.1.5 on 2025-01-20 23:24

import django.db.models.deletion
import tssite.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0029_auto_20200525_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['series_sequence', 'division_sequence', 'segment_sequence', 'section_sequence', 'unit_sequence', 'part_sequence', 'series_sequence', '-date']},
        ),
        migrations.AlterField(
            model_name='teamim',
            name='audio',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to=tssite.models.get_teamim_audio_location),
        ),
        migrations.CreateModel(
            name='SchedulePause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.schedule')),
            ],
        ),
    ]
