# Generated by Django 5.1.5 on 2025-01-21 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0030_schedule_alter_class_options_alter_teamim_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepause',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tssite.schedule'),
        ),
    ]
