# Generated by Django 5.1.5 on 2025-10-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0031_alter_schedulepause_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='schedulepause',
            options={'ordering': ['start_date', 'end_date']},
        ),
    ]
