# Generated by Django 5.1.5 on 2025-10-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tssite', '0032_alter_schedule_options_alter_schedulepause_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talmudsponsor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talmudstudy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamim',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
