name: CI

on:
  push:

jobs:
  lint-and-migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Install dependencies
      run: uv sync
      
    - name: Install Ruff
      run: uv add --dev ruff
      
    - name: Run Ruff linting
      run: uv run ruff check .
      
    - name: Run Ruff formatting check
      run: uv run ruff format --check .
      
    - name: Set environment variables
      run: |
        echo "DJANGO_SETTINGS_MODULE=tsAdmin.settings" >> $GITHUB_ENV
        
    - name: Run Django migration check
      run: uv run python manage.py makemigrations --check --dry-run
      
    - name: Run Django migration check (with existing migrations)
      run: uv run python manage.py migrate --check
